//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicSchoolWepApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ogrenciler()
        {
            this.tbl_Notlar = new HashSet<tbl_Notlar>();
        }
    
        public int OgrID { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public Nullable<int> OgrKulup { get; set; }
        public string OgrCinsiyet { get; set; }
        public string OgrTelefon { get; set; }
        public string OgrMail { get; set; }
        public string OgrFotograf { get; set; }
        public string OgrSifre { get; set; }
    
        public virtual tbl_Kulupler tbl_Kulupler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Notlar> tbl_Notlar { get; set; }
    }
}
